### ISSUE TITLE
Elections data scraping code is stale... again

### ISSUE THREAD

**Issue by JohnCRuf** [JohnCRuf/alderman_machine#34]
The election data scraping code is once again stale. Need to be updated.

**Comment by JohnCRuf** [comment]
Is there a more permanent solution to this?

**Comment by tmalthouse** [comment]
I’m out of the house RN so can’t check, but I haven’t had issues with my election scraper going stale. I’ll check whether it works after getting back, but I think the data I pull should be sufficiently granular for your work.

Thomas

**Comment by JohnCRuf** [comment]
No problem, I think I have an easy fix for it.

**Comment by JohnCRuf** [comment]
Issue is resolved as #35 has been merged
