### ISSUE TITLE
Gather spatial data using census and google API's

### ISSUE THREAD

**Issue by JohnCRuf** [JohnCRuf/alderman_machine#7]
Develop an R or Python script that takes the location information from the menu data, processes it so that the census and/or Google location APIs can handle it, and obtains geographic coordinates. Then match this data with Chicago Political Map data, especially voting precinct data.

**Comment by smacmullan** [comment]
Should you need to do more geocoding at some point, I've had relative success using the Chicago street center lines data set to find the coordinates of intersecting streets. 

Dataset: https://data.cityofchicago.org/Transportation/Street-Center-Lines/6imu-meau
WIP API implementation by @kollerbud: https://github.com/smacmullan/chicago-participatory-urbanism/blob/main/chicago_participatory_urbanism/geocoder_api.py

**Comment by JohnCRuf** [comment]
Closing this for now, the current geolocation code seems to work well enough. I'll create a new issue for the WIP API.
